### ISSUE TITLE
Dir.home

### ISSUE THREAD

**Issue by wesyoung** [arxopia/uirusu#10]
testing on aws; might want to go with this instead:

```
CONFIG_FILE = "#{ENV['HOME']}/.uirusu"
```

https://github.com/arxopia/uirusu/blob/master/lib/uirusu.rb#L34

haven't done extensive testing; but aws doesn't like `Dir.home` in it's default configuration of the nodes.

fwiw.

**Comment by hammackj** [comment]
Thanks. I will push a update soon.

**Comment by wesyoung** [comment]
i might have another PR (doing a bit of testing first), but certain types of deployments (circleci) don't like "requiring" too much in the gemspec itself, which 'require uirusu' ends up doing [recursively].

https://github.com/arxopia/uirusu/blob/master/lib/uirusu.rb#L27

instead of having both the constants (VT_API, etc) in uirusu.rb, maybe create a lib/uirusu/contants.rb that has that in it, something like:

https://github.com/arxopia/uirusu/compare/master...csirtgadgets:master

and require 'uirusu/contants' to get the constants out into the gemspec file?

like i said; still doing a bit of testing first to make sure it doesn't break anything else...'

**Comment by hammackj** [comment]
Let me know how the testing goes. I think ENV['HOME'] might fail on Windows also, granted I haven't tested on Windows though.

**Comment by wesyoung** [comment]
hrm, good point. you might want to re-consider how this is being done. instead of relying on something like ENV["HOME"] or Dir... a lot of rails apps (where we're finding it useful), esp in amazon web services land are both:

+ avoiding the use of config files where possible OR
+ enable the setting of a config through something like Env['UIRUSU_CONFIG'] but also enabling all the options a config might set, be set through the env as well, such as ENV["UIRUSU_VT_TOKEN"], etc.

make sense?

**Comment by hammackj** [comment]
I will think of a solution for supporting both rails and cli apps. =)

**Comment by hammackj** [comment]
This should be addressed in v1.0.1, live now. Please let me know if you require more.
