### ISSUE TITLE
Unknown Server error (400) when running `ruby script.rb`

### ISSUE THREAD

**Issue by naltun** [arxopia/uirusu#13]
When I run `ruby scan.rb` I get:

```
/usr/local/rvm/gems/ruby-2.3.0/gems/uirusu-1.0.2/lib/uirusu.rb:73:in `parse_response': Unknown Server error. (400) (RuntimeError)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/uirusu-1.0.2/lib/uirusu.rb:48:in `query_api'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/uirusu-1.0.2/lib/uirusu/vturl.rb:61:in `query_report'
        from scan.rb:6:in `<main>'
```

My code is as follows:
```
require 'uirusu'

urls = "url1.com\nurl2.com\url3.com\url4.com[,...urln.com\n]" # I'm using multiple URLs; VirusTotal exemplifies in their Python script that you can append \n between URLs to query multiple entries
API_KEY = "not_for_you"

results = Uirusu::VTUrl.query_report(API_KEY, urls)
result  = Uirusu::VTResult.new(urls, results)
if result != nil then print result.to_stdout else puts "Sorry, there was an error." end
```

Why would I get this error? Have you encountered this before?

**Comment by hammackj** [comment]
Does it work with 1 hostname?

**Comment by naltun** [comment]
It does work with just one hostname. Maybe that should be a future feature, to work with multiple URLs.

**Comment by hammackj** [comment]
I'll take a look at it.

**Comment by hammackj** [comment]
I fixed a few bugs and multiple URLs can be submitted via scan_urls, I haven't updated VTurl.query_report yet, but it is easy to customize to support, just looping the result from the query to get the multi scan IDs then querying each of those or bulking those. Going to go ahead and close this. As I am moving the repo to my personal github.
