### ISSUE TITLE
Doesn't handle HTTP response code 204

### ISSUE THREAD

**Issue by JasonPoll** [arxopia/uirusu#3]
According to the VT documentation at https://www.virustotal.com/en/documentation/public-api/ HTTP response code 204 is the "API request limit reached" response code, not 429.  When 204 is returned, it's raised as an _Unknown Server error._ instead of _Virustotal limit reached. Try again later._

**Comment by hammackj** [comment]
I merged your pull request. Does that solve this problem for you?

**Comment by JasonPoll** [comment]
Hey, thank you for your quick response and considering my pull request.

It certainly does help.  I’ve had to go into my application and implement some self-throttling and this will help.

Have you considered raising custom errors instead of StandardError so that a developer could more easily handle the various exception scenarios?  So instead of just raise “Virustotal limit reached. Try again later” it could be raise VirusTotalLimitError.new().  With this change, code that uses uirusu could handle that error specifically, and throttle their API calls.

I’d be happy to make a pull request for it if you’d like. :)

—JP



From: Jacob Hammack
Reply-To: arxopia/uirusu
Date: Monday, August 31, 2015 at 1:27 PM
To: arxopia/uirusu
Cc: Jason Poll
Subject: Re: [uirusu] Doesn't handle HTTP response code 204 (#3)


I merged your pull request. Does that solve this problem for you?

**Comment by hammackj** [comment]
Feel free to submit a pull request. I haven't done much with the code
lately.

-Jacob

On Monday, August 31, 2015, Jason Poll <notifications@github.com> wrote:

> Hey, thank you for your quick response and considering my pull request.
>
> It certainly does help. I’ve had to go into my application and implement
> some self-throttling and this will help.
>
> Have you considered raising custom errors instead of StandardError so that
> a developer could more easily handle the various exception scenarios? So
> instead of just raise “Virustotal limit reached. Try again later” it could
> be raise VirusTotalLimitError.new(). With this change, code that uses
> uirusu could handle that error specifically, and throttle their API calls.
>
> I’d be happy to make a pull request for it if you’d like. :)
>
> —JP
>
>
>
> From: Jacob Hammack
> Reply-To: arxopia/uirusu
> Date: Monday, August 31, 2015 at 1:27 PM
> To: arxopia/uirusu
> Cc: Jason Poll
> Subject: Re: [uirusu] Doesn't handle HTTP response code 204 (#3)
>
>
> I merged your pull request. Does that solve this problem for you?
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/arxopia/uirusu/issues/3#issuecomment-136454274>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arxopia/uirusu/issues/3#issuecomment-136484471>.
>


-- 
Jacob Hammack
Jacob.Hammack@Hammackj.com
(210) 355-0036
http://www.hammackj.com

**Comment by hammackj** [comment]
I think this got resolved by your PR. If not please re-open.
