### ISSUE TITLE
Results from scan_and_wait are double-wrapped.

### ISSUE THREAD

**Issue by kitplummer** [arxopia/uirusu#6]
➜  uirusu git:(master) bin/uirusu --verbose -j -u ~/Downloads/GoogleVoiceAndVideoSetup.dmg
[+] Adding file /Users/kplummer/Downloads/GoogleVoiceAndVideoSetup.dmg
[*] Attempting to rescan /Users/kplummer/Downloads/GoogleVoiceAndVideoSetup.dmg
[*] Attempting to parse the results for: 0b8eebc6b06476af36ebd943fe64a4c941db874cc21b64e184230ae8d03b6ce6
/Users/kplummer/Codes/uirusu/lib/uirusu/vtresult.rb:127:in `to_json': undefined method `map' for nil:NilClass (NoMethodError)
	from /Users/kplummer/Codes/uirusu/lib/uirusu/cli/application.rb:328:in `block in main'
	from /Users/kplummer/Codes/uirusu/lib/uirusu/cli/application.rb:325:in `each'
	from /Users/kplummer/Codes/uirusu/lib/uirusu/cli/application.rb:325:in `each_with_index'
	from /Users/kplummer/Codes/uirusu/lib/uirusu/cli/application.rb:325:in `main'
	from bin/uirusu:37:in `<main>'

This is because the actual info is in results[0][0] and results[0][1].  Looking at the returned value from I verified this.

Think it is just because of the Array brackets around the return value.  Removed and tested everything it seems to work.  Can you verify that you see this too?  I noticed it when uploading a file.

I'll submit a PR which you can accept if it solves the problem for you too.

**Comment by hammackj** [comment]
Solved. Thank you for the PR.
